function  WWHBookData_Files(P)
{
P.fA("Using This Help File","Rfm.html");
P.fA("Conventions Used in this Help File","Rfm2.html");
P.fA("Contacting Technical Support","Rfm3.html");
P.fA("Quick Start Connect","quikstart.html");
P.fA("Connecting and Testing on Windows","Rquikstart2.html");
P.fA("Connecting and Testing on UNIX","Rquikstart3.html");
P.fA("Using DataDirect Connect\u00ae for ODBC","usingodbc.html");
P.fA("About DataDirect Connect\u00ae for ODBC Drivers","Rstart2.html");
P.fA("Environment-Specific Information","Rstart3.html");
P.fA("Using Connection Failover","Rstart4.html");
P.fA("Using Client Load Balancing ","Rstart5.html");
P.fA("Using Connection Retry","Rstart6.html");
P.fA("Binding Parameter Markers","Rstart7.html");
P.fA("Version String Information","Rstart8.html");
P.fA("Retrieving Data Type Information","Rstart9.html");
P.fA("The DB2 Wire Protocol Driver","db2.html");
P.fA("Driver Requirements","Rdb22.html");
P.fA("Binding","Rdb23.html");
P.fA("Configuring Data Sources","Rdb24.html");
P.fA("Connecting to a Data Source Using a Logon Dialog Box","Rdb25.html");
P.fA("Connecting to a Data Source Using a Connection String","Rdb26.html");
P.fA("Performance Considerations","Rdb27.html");
P.fA("Data Types","Rdb28.html");
P.fA("Unicode Support","Rdb29.html");
P.fA("Configuring Connection Failover","Rdb210.html");
P.fA("Persisting a Result Set as an XML Data File","Rdb211.html");
P.fA("Stored Procedure Support","Rdb212.html");
P.fA("Isolation and Lock Levels Supported","Rdb213.html");
P.fA("ODBC Conformance Level","Rdb214.html");
P.fA("Number of Connections and Statements Supported","Rdb215.html");
P.fA("Using Arrays of Parameters","Rdb216.html");
P.fA("IBM to IANA Code Page Values","Rdb217.html");
P.fA("The Informix Wire Protocol Driver","informix.html");
P.fA("Driver Requirements","Rinf_wp2.html");
P.fA("Configuring Data Sources","Rinf_wp3.html");
P.fA("Connecting to a Data Source Using a Logon Dialog Box","Rinf_wp4.html");
P.fA("Connecting to a Data Source Using a Connection String","Rinf_wp5.html");
P.fA("Performance Considerations","Rinf_wp6.html");
P.fA("Data Types","Rinf_wp7.html");
P.fA("MTS Support","Rinf_wp8.html");
P.fA("Configuring Connection Failover","Rinf_wp9.html");
P.fA("Persisting a Result Set as an XML Data File","Rinf_wp10.html");
P.fA("Isolation and Lock Levels Supported","Rinf_wp11.html");
P.fA("ODBC Conformance Level","Rinf_wp12.html");
P.fA("Number of Connections and Statements Supported","Rinf_wp13.html");
P.fA("The Oracle Wire Protocol Driver","oracle.html");
P.fA("Driver Requirements","RORACLEwp2.html");
P.fA("Configuring Data Sources","RORACLEwp3.html");
P.fA("Connecting to a Data Source Using a Logon Dialog Box","RORACLEwp4.html");
P.fA("Connecting to a Data Source Using a Connection String","RORACLEwp5.html");
P.fA("Performance Considerations","RORACLEwp6.html");
P.fA("OS Authentication","RORACLEwp7.html");
P.fA("Support for Oracle RAC","RORACLEwp8.html");
P.fA("Data Types","RORACLEwp9.html");
P.fA("Unicode Support","RORACLEwp10.html");
P.fA("Configuring Connection Failover","RORACLEwp11.html");
P.fA("Persisting a Result Set as an XML Data File","RORACLEwp12.html");
P.fA("MTS Support","RORACLEwp13.html");
P.fA("Stored Procedure Results","RORACLEwp14.html");
P.fA("Support of Materialized Views","RORACLEwp15.html");
P.fA("Isolation and Lock Levels Supported","RORACLEwp16.html");
P.fA("ODBC Conformance Level","RORACLEwp17.html");
P.fA("Number of Connections and Statements Supported","RORACLEwp18.html");
P.fA("Using Arrays of Parameters","RORACLEwp19.html");
P.fA("The SQL Server Wire Protocol Driver","sqlserver.html");
P.fA("Driver Requirements","Rsqlsrv2.html");
P.fA("Configuring Data Sources","Rsqlsrv3.html");
P.fA("Connecting to a Data Source Using a Logon Dialog Box","Rsqlsrv4.html");
P.fA("Connecting to a Data Source Using a Connection String","Rsqlsrv5.html");
P.fA("Data Types","Rsqlsrv6.html");
P.fA("Unicode Support","Rsqlsrv7.html");
P.fA("Configuring Connection Failover","Rsqlsrv8.html");
P.fA("Isolation and Lock Levels Supported","Rsqlsrv9.html");
P.fA("ODBC Conformance Level","Rsqlsrv10.html");
P.fA("Number of Connections and Statements Supported","Rsqlsrv11.html");
P.fA("Using Arrays of Parameters","Rsqlsrv12.html");
P.fA("The Sybase Wire Protocol Driver","sybase.html");
P.fA("Driver Requirements","Rase2.html");
P.fA("Configuring Data Sources","Rase3.html");
P.fA("Connecting to a Data Source Using a Logon Dialog Box","Rase4.html");
P.fA("Connecting to a Data Source Using a Connection String","Rase5.html");
P.fA("Performance Considerations","Rase6.html");
P.fA("Data Types","Rase7.html");
P.fA("MTS Support","Rase8.html");
P.fA("Unicode Support","Rase9.html");
P.fA("Configuring Connection Failover","Rase10.html");
P.fA("Persisting a Result Set as an XML Data File","Rase11.html");
P.fA("Support for Query Timeout","Rase12.html");
P.fA("Isolation and Lock Levels Supported","Rase13.html");
P.fA("ODBC Conformance Level","Rase14.html");
P.fA("Number of Connections and Statements Supported","Rase15.html");
P.fA("Using Arrays of Parameters","Rase16.html");
P.fA("The Btrieve (Pervasive.SQL) Driver","btrieve.html");
P.fA("Driver Requirements","Rbtrieve2.html");
P.fA("Managing Databases","Rbtrieve3.html");
P.fA("Transactions","Rbtrieve4.html");
P.fA("Configuring Data Sources","Rbtrieve5.html");
P.fA("Defining Table Structure","Rbtrieve6.html");
P.fA("Connecting to a Data Source Using a Connection String","Rbtrieve7.html");
P.fA("Data Types","Rbtrieve8.html");
P.fA("Indexes","Rbtrieve9.html");
P.fA("Column Names","Rbtrieve10.html");
P.fA("Select Statement","Rbtrieve11.html");
P.fA("Alter Table Statement","Rbtrieve12.html");
P.fA("Create and Drop Index Statements","Rbtrieve13.html");
P.fA("Isolation and Lock Levels Supported","Rbtrieve14.html");
P.fA("ODBC Conformance Level","Rbtrieve15.html");
P.fA("Number of Connections and Statements Supported","Rbtrieve16.html");
P.fA("The dBASE Driver","dbase.html");
P.fA("Driver Requirements","Rdbasfox2.html");
P.fA("Configuring Data Sources","Rdbasfox3.html");
P.fA("Defining Index Attributes","Rdbasfox4.html");
P.fA("Defining Index Attributes on UNIX","Rdbasfox5.html");
P.fA("Connecting to a Data Source Using a Connection String","Rdbasfox6.html");
P.fA("Data Types","Rdbasfox7.html");
P.fA("Column Names","Rdbasfox8.html");
P.fA("Select Statement","Rdbasfox9.html");
P.fA("Alter Table Statement","Rdbasfox10.html");
P.fA("Create and Drop Index Statements","Rdbasfox11.html");
P.fA("Pack Statement","Rdbasfox12.html");
P.fA("SQL Statements for FoxPro 3.0 Database Containers","Rdbasfox13.html");
P.fA("Locking","Rdbasfox14.html");
P.fA("Isolation and Lock Levels Supported","Rdbasfox15.html");
P.fA("ODBC Conformance Level","Rdbasfox16.html");
P.fA("Number of Connections and Statements Supported","Rdbasfox17.html");
P.fA("The Informix Driver","informixclient.html");
P.fA("Driver Requirements","Rinfx2.html");
P.fA("Configuring Data Sources","Rinfx3.html");
P.fA("Connecting to a Data Source Using a Logon Dialog Box","Rinfx4.html");
P.fA("Connecting to a Data Source Using a Connection String","Rinfx5.html");
P.fA("Performance Considerations","Rinfx6.html");
P.fA("Data Types","Rinfx7.html");
P.fA("MTS Support","Rinfx8.html");
P.fA("Persisting a Result Set as an XML Data File","Rinfx9.html");
P.fA("Isolation and Lock Levels Supported","Rinfx10.html");
P.fA("ODBC Conformance Level","Rinfx11.html");
P.fA("Number of Connections and Statements Supported","Rinfx12.html");
P.fA("The Oracle Driver ","oracleclient.html");
P.fA("Driver Requirements","Roracle2.html");
P.fA("Configuring Data Sources","Roracle3.html");
P.fA("Connecting to a Data Source Using a Logon Dialog Box","Roracle4.html");
P.fA("Connecting to a Data Source Using a Connection String","Roracle5.html");
P.fA("Performance Considerations","Roracle6.html");
P.fA("OS Authentication","Roracle7.html");
P.fA("Support for Oracle RAC","Roracle8.html");
P.fA("Data Types","Roracle9.html");
P.fA("MTS Support","Roracle10.html");
P.fA("Unicode Support","Roracle11.html");
P.fA("Configuring Connection Failover","Roracle12.html");
P.fA("Persisting a Result Set as an XML Data File","Roracle13.html");
P.fA("Stored Procedure Results","Roracle14.html");
P.fA("Support of Materialized Views","Roracle15.html");
P.fA("Isolation and Lock Levels Supported","Roracle16.html");
P.fA("ODBC Conformance Level","Roracle17.html");
P.fA("Number of Connections and Statements Supported","Roracle18.html");
P.fA("Using Arrays of Parameters","Roracle19.html");
P.fA("The Paradox Driver","paradox.html");
P.fA("Driver Requirements","Rparadox2.html");
P.fA("Multiuser Access to Database Files","Rparadox3.html");
P.fA("Configuring Data Sources","Rparadox4.html");
P.fA("Connecting to a Data Source Using a Connection String","Rparadox5.html");
P.fA("Data Types","Rparadox6.html");
P.fA("Select Statement","Rparadox7.html");
P.fA("Alter Table Statement","Rparadox8.html");
P.fA("Create Table Statement","Rparadox9.html");
P.fA("Password Protection","Rparadox10.html");
P.fA("Index Files","Rparadox11.html");
P.fA("Create and Drop Index Statements","Rparadox12.html");
P.fA("Transactions","Rparadox13.html");
P.fA("Isolation and Lock Levels Supported","Rparadox14.html");
P.fA("ODBC Conformance Level","Rparadox15.html");
P.fA("Number of Connections and Statements Supported","Rparadox16.html");
P.fA("The Progress OpenEdge Driver","progress10.html");
P.fA("Driver Requirements","Rprog102.html");
P.fA("Configuring Data Sources","Rprog103.html");
P.fA("Connecting to a Data Source Using a Logon Dialog Box","Rprog104.html");
P.fA("Connecting to a Data Source Using a Connection String","Rprog105.html");
P.fA("Data Types","Rprog106.html");
P.fA("Isolation and Lock Levels Supported","Rprog107.html");
P.fA("ODBC Conformance Level","Rprog108.html");
P.fA("Number of Connections and Statements Supported","Rprog109.html");
P.fA("The Progress SQL92 Driver","progress9.html");
P.fA("Driver Requirements","Rprog92.html");
P.fA("Configuring Data Sources","Rprog93.html");
P.fA("Connecting to a Data Source Using a Logon Dialog Box","Rprog94.html");
P.fA("Connecting to a Data Source Using a Connection String","Rprog95.html");
P.fA("Data Types","Rprog96.html");
P.fA("Isolation and Lock Levels Supported","Rprog97.html");
P.fA("ODBC Conformance Level","Rprog98.html");
P.fA("Number of Connections and Statements Supported","Rprog99.html");
P.fA("The Text Driver","text.html");
P.fA("Driver Requirements","Rtext2.html");
P.fA("Formats for Text Files","Rtext3.html");
P.fA("Configuring Data Sources","Rtext4.html");
P.fA("Defining Table Structure","Rtext5.html");
P.fA("Defining Table Structure on UNIX Platforms","Rtext6.html");
P.fA("Date Masks","Rtext7.html");
P.fA("Connecting to a Data Source Using a Connection String","Rtext8.html");
P.fA("Data Types","Rtext9.html");
P.fA("Select Statement","Rtext10.html");
P.fA("Alter Table Statement","Rtext11.html");
P.fA("ODBC Conformance Level","Rtext12.html");
P.fA("Number of Connections and Statements Supported","Rtext13.html");
P.fA("The XML Driver","xml.html");
P.fA("Driver Requirements","Rxml2.html");
P.fA("Supported Tabular Formats for XML Documents","Rxml3.html");
P.fA("Hierarchical-Formatted XML Document Support","Rxml4.html");
P.fA("Defining Locations","Rxml5.html");
P.fA("Specifying Table Names in SQL Statements","Rxml6.html");
P.fA("Configuring Data Sources","Rxml7.html");
P.fA("Connecting to a Data Source Using a Logon Dialog Box","Rxml8.html");
P.fA("Connecting to a Data Source Using a Connection String","Rxml9.html");
P.fA("Using Hints for Tabular-Formatted XML Documents","Rxml10.html");
P.fA("Data Types","Rxml11.html");
P.fA("Unicode Support","Rxml12.html");
P.fA("Persisting a Result Set as an XML Data File","Rxml13.html");
P.fA("ODBC Conformance Level","Rxml14.html");
P.fA("Number of Connections and Statements Supported","Rxml15.html");
P.fA("SQL Supported","Rxml16.html");
P.fA("SQL for Flat-File Drivers","sqlflat.html");
P.fA("Select Statement","RSGLFLAT2.html");
P.fA("Create and Drop Table Statements","RSGLFLAT3.html");
P.fA("Insert Statement","RSGLFLAT4.html");
P.fA("Update Statement","RSGLFLAT5.html");
P.fA("Delete Statement","RSGLFLAT6.html");
P.fA("Reserved Keywords","RSGLFLAT7.html");
P.fA("ODBC API and Scalar Functions","scalar.html");
P.fA("API Functions","Rapiscal2.html");
P.fA("Scalar Functions","Rapiscal3.html");
P.fA("Locking and Isolation Levels","locking.html");
P.fA("Locking","Rlock2.html");
P.fA("Isolation Levels","Rlock3.html");
P.fA("Locking Modes and Levels","Rlock4.html");
P.fA("The UNIX Environments","unixenviron.html");
P.fA("Environment Variables","Runixenv2.html");
P.fA("The ivtestlib Tool","Runixenv3.html");
P.fA("The System Information File (odbc.ini)","Runixenv4.html");
P.fA("demoodbc","Runixenv5.html");
P.fA("example","Runixenv6.html");
P.fA("DSN-less Connections","Runixenv7.html");
P.fA("UTF-16 Applications on UNIX","Runixenv8.html");
P.fA("Values for IANAAppCodePage Connection String Attribute","appcodepage.html");
P.fA("Diagnostic Tools, Error Messages, and Troubleshooting","diagnostic.html");
P.fA("Diagnostic Tools","Rdiagnostic2.html");
P.fA("Error Messages","Rdiagnostic3.html");
P.fA("Troubleshooting","Rdiagnostic4.html");
P.fA("Glossary","ODBCglossary.html");
}
